version: '3'
services: 
    server:
        container_name: node-docker
        restart: always
        build: .
        command: npm start
        ports: 
            - 5000:5000
        links: 
            - 'mongo'
    mongo:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: Mongoose55
            MONGO_INITDB_ROOT_PASSWORD: Wifi5757
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
          
volumes:
    mongodb_data_container: